name: usecasedepot-r # Name of the instance-secret, indicating it's for read-only access.
version: v1 # Manifest Version    
type: instance-secret # Resource-type
description:  Read-only secret for Postgres database   # Optional: Brief description of the instance-secret's purpose.
layer: user # DataOS Layer                 
instance-secret:
  type: key-value-properties  # Type of Instance-secret
  acl: r                 # Access control level, set to 'r' for read-only access.
  data:                       
    azureendpointsuffix: core.windows.net # Endpoint suffix for the Azure storage account.
    azurestorageaccountkey: WxC95Okw7mPX2dJLgqBY0x55ef2LF65NaVuV9cjjPXFpcJD4iYVuXLWIMd0ZAF4s8zTDlyVGW62z+AStGNO+Eg==
    azurestorageaccountname: storagesog # Name of the Azure storage account.