name: usecasedepot-rw  # Name of the instance-secret, indicating it's for read-write access.
version: v1 # Manifest Version           
type: instance-secret # Resource-type
description: Read write secret for Postgres database    # Optional: Brief description of the instance-secret's purpose.
layer: user # DataOS Layer                 
instance-secret:
  type: key-value-properties  # Type of Instance-secret
  acl: rw                     # Access control level, set to 'rw' for read-write access.
  data:                       
    azureendpointsuffix: core.windows.net # Endpoint suffix for the Azure storage account.
    azurestorageaccountkey: WxC95Okw7mPX2dJLgqBY0x55ef2LF65NaVuV9cjjPXFpcJD4iYVuXLWIMd0ZAF4s8zTDlyVGW62z+AStGNO+Eg==
    azurestorageaccountname: storagesog # Name of the Azure storage account.